server:
  port: 8080

spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database: ${DATABASE}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password : ${REDIS_PASSWORD}

jwt:
  secret: ${SECRET}

token:
  exp:
    access-token: ${ACCESS_TOKEN_EXP:1800}
    refresh-token: ${REFRESH_TOKEN_EXP:43200}

cloud:
  aws:
    s3:
      url :
      bucket: ${S3_BUCKET}
#    credentials:
#      access-key: ${S3_ACCESS_KEY}
#      secret-key: ${S3_REFRESH_KEY}
#    region:
#      static : ${REGION}
#    stack:
#      auto: ${AUTO}
#
#sms :
#  apikey : ${API_KEY}
#  secret : ${SECRET_KEY}
#  phoneNumber : ${PHONE_NUMBER}